### ISSUE TITLE
NeurIPS 21 passed and the code is not even released ...

### ISSUE THREAD

**Issue by huckiyang** [xionghuichen/CODAS#2]
I just come over this work but found that the code is not even (trying to) released. 

This may lead to some reproducibility concerns as baseline studies and also degrade the impact of your work. 

Any idea @xionghuichen ?

**Comment by xionghuichen** [comment]
Thanks for your attention. We have refactored the code for simplicity. It is being retested in all of the proposed experiments to keep the reproducibility. We will upload the code and send a reminder to you as soon as possible.

**Comment by huckiyang** [comment]
Honestly, as a reviewer in both NeuIPS and ICML, it is really sad to see a process like this. 

I did not work on this specific topic (e.g., RL for domain adaptation) but it is clearly negative to the ML communities. 

Good luck …

**Comment by jiangsy** [comment]
I think there is perhaps some misunderstanding. This repo is not a fake one. If you are really interested in our work, you can try the dev branch which is runnable on all MuJoCo tasks. The rest work on HMS task is expected to be done by the end of this year.

We are sorry for a delayed open-source and thanks for your interest in our work.

**Comment by huckiyang** [comment]
@jiangsy I see. You may consider to add the existing dev link in the ‘main’ readme since direct reading the main repo of your work is almost like an empty shell. 

Good luck then,
